spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/basic_project?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  ### 配置Redis
  redis:
    database: 0
    host: 192.168.56.10
    port: 6379
    password: 123456